import type { WorkoutDef, WorkoutType } from './types';

export const WORKOUT_ORDER: WorkoutType[] = ['push', 'pull', 'legs', 'upper', 'lower'];

export const PROGRAM: WorkoutDef[] = [
  {
    type: 'push',
    name: 'Push',
    exercises: [
      {
        id: 'flat_bb_bench',
        name: 'Flat Barbell Bench Press',
        sets: 3,
        repRange: [5, 8],
        effort: '2 RIR',
        rest: 180,
        cue: '3s controlled descent to mid-sternum, elbows ~45–60°',
        why: 'The slight elbow tuck protects the shoulder joint and keeps stress on the pec. A 3-second eccentric raises time under tension and micro-damage for a stronger hypertrophic signal. Stopping 2 reps short of failure on a spinal-load lift meaningfully reduces injury risk with negligible hypertrophy cost.',
        increment: { lb: 5, kg: 2.5 },
        warmupSets: true,
      },
      {
        id: 'standing_ohp',
        name: 'Standing Overhead Press',
        sets: 3,
        repRange: [6, 8],
        effort: '2 RIR',
        rest: 180,
        cue: 'Brace core/glutes, bar path stays close to the face',
        why: 'A vertical bar path minimises the shoulder moment arm. Core and glute tension creates a rigid base that transfers leg drive into the lift and protects the lumbar spine under load.',
        increment: { lb: 5, kg: 2.5 },
        warmupSets: true,
      },
      {
        id: 'incline_db_bench',
        name: 'Incline Dumbbell Bench (30°)',
        sets: 3,
        repRange: [8, 12],
        effort: '1–2 RIR',
        rest: 120,
        cue: 'Lower to a deep stretch, elbows ~45°',
        why: 'The 30° incline biases the clavicular (upper) head of the pec while still allowing deep shoulder extension — the stretched position is where most hypertrophic stimulus occurs. Dumbbells allow greater ROM than a barbell at this angle.',
        increment: { lb: 5, kg: 2 },
      },
      {
        id: 'db_lateral_raise',
        name: 'Dumbbell Lateral Raise',
        sets: 3,
        repRange: [12, 15],
        effort: '1 RIR',
        rest: 90,
        cue: 'Lean forward 5–10°, lead with elbows',
        why: 'The forward lean shifts the line of pull so the medial delt is maximally loaded through the full ROM. Leading with elbows prevents the upper trap from dominating the movement.',
        increment: { lb: 5, kg: 2 },
      },
      {
        id: 'overhead_cable_tri',
        name: 'Overhead Cable Tricep Extension',
        sets: 3,
        repRange: [10, 12],
        effort: '1 RIR',
        rest: 90,
        cue: 'Elbows pinned by ears, flare rope at lockout',
        why: 'The overhead position stretches the long head of the tricep (the largest head) where mechanical tension is highest. Flaring the rope at lockout emphasises full contraction of the lateral and medial heads.',
        increment: { lb: 5, kg: 2 },
      },
    ],
  },
  {
    type: 'pull',
    name: 'Pull',
    exercises: [
      {
        id: 'weighted_pull_ups',
        name: 'Weighted Pull-Ups / Neutral Chin-Ups',
        sets: 3,
        repRange: [6, 8],
        effort: '2 RIR',
        rest: 180,
        cue: '3s controlled descent to a full dead hang',
        why: 'The dead hang fully lengthens the lat and produces peak mechanical tension at the bottom. A 3-second eccentric keeps time-under-tension high without adding extra fatigue-heavy sets.',
        increment: { lb: 5, kg: 2.5 },
        warmupSets: true,
      },
      {
        id: 'tbar_row',
        name: 'Chest-Supported T-Bar Row',
        sets: 3,
        repRange: [8, 10],
        effort: '1–2 RIR',
        rest: 120,
        cue: 'Drive elbows back/up, protract shoulder blades at the stretch',
        why: 'The chest pad eliminates lower-back fatigue so you can push closer to failure on a heavy horizontal pull. Shoulder-blade protraction at the bottom maximises lat stretch and the subsequent contraction signal.',
        increment: { lb: 5, kg: 2.5 },
        warmupSets: true,
      },
      {
        id: 'lat_pulldown',
        name: 'Lat Pulldown',
        sets: 3,
        repRange: [10, 12],
        effort: '1 RIR',
        rest: 120,
        cue: 'Lean back 10–15°, pull to upper chest, no torso swing',
        why: 'A slight lean shifts the line of pull to maximise lat involvement over the teres and rear delt. Torso swing is a momentum cheat that reduces stimulus and risks disc loading.',
        increment: { lb: 5, kg: 2 },
      },
      {
        id: 'cable_rear_delt_fly',
        name: 'Cable Rear Delt Fly',
        sets: 3,
        repRange: [12, 15],
        effort: '1 RIR',
        rest: 90,
        cue: 'Slight elbow bend, pull horizontally',
        why: 'A horizontal pull path targets the posterior deltoid rather than the upper trap. Cable tension stays constant through the full ROM, unlike a dumbbell which loses load at the contracted position.',
        increment: { lb: 5, kg: 2 },
      },
      {
        id: 'bayesian_cable_curl',
        name: 'Unilateral Bayesian Cable Curl',
        sets: 4,
        repRange: [10, 12],
        effort: '1 RIR (sets 1–3), failure (set 4)',
        rest: 90,
        cue: 'Arm starts behind the torso for a deep stretch',
        why: 'The behind-the-body cable position loads the bicep in its lengthened state — where most hypertrophic stimulus occurs. Reaching failure only on the last set limits total fatigue while providing a maximal overload signal.',
        increment: { lb: 5, kg: 2 },
        lastSetFailure: true,
      },
    ],
  },
  {
    type: 'legs',
    name: 'Legs',
    exercises: [
      {
        id: 'barbell_squat',
        name: 'Barbell Back Squat',
        sets: 3,
        repRange: [6, 8],
        effort: '2 RIR',
        rest: 180,
        cue: 'High-bar, brace, thighs to at least parallel',
        why: 'High-bar positioning creates a more upright torso and shifts load toward the quads. Stopping 2 reps short of failure on a heavy loaded-spine movement meaningfully reduces injury risk with negligible hypertrophy cost.',
        increment: { lb: 10, kg: 5 },
        warmupSets: true,
      },
      {
        id: 'rdl',
        name: 'Romanian Deadlift',
        sets: 3,
        repRange: [8, 10],
        effort: '2 RIR',
        rest: 180,
        cue: 'Hips back, slight knee bend, bar stays on the legs',
        why: 'The RDL is a hinge, not a squat — keeping the bar close to the leg maintains the moment arm and forces hamstring-dominant loading. Bar contact is the tactile feedback that keeps the movement pattern honest.',
        increment: { lb: 10, kg: 5 },
        warmupSets: true,
      },
      {
        id: 'leg_press',
        name: 'Leg Press',
        sets: 3,
        repRange: [10, 12],
        effort: '1–2 RIR',
        rest: 120,
        cue: 'Knees to ~90°, stop short of lockout',
        why: 'Stopping short of lockout keeps the quads under continuous tension and avoids shunting load to the knee joint capsule. The 90° depth ensures adequate quad length for a hypertrophic stretch stimulus.',
        increment: { lb: 20, kg: 10 },
        warmupSets: true,
      },
      {
        id: 'standing_calf_raise',
        name: 'Standing (Smith) Calf Raise',
        sets: 4,
        repRange: [10, 15],
        effort: '1 RIR (sets 1–3), failure + stretched partials (set 4)',
        rest: 90,
        cue: 'Toes out 45°, pause 3s at the deep stretch, then drive up',
        why: 'Toes out biases the medial gastrocnemius. The 3-second pause eliminates the stretch-shortening reflex so each rep is purely muscular. Stretched partials after failure maximise time-under-tension at the most mechanically advantageous position.',
        increment: { lb: 5, kg: 2.5 },
        lastSetFailure: true,
      },
      {
        id: 'lying_leg_curl',
        name: 'Lying Leg Curl',
        sets: 3,
        repRange: [10, 12],
        effort: '1 RIR',
        rest: 90,
        cue: 'Squeeze at the top, control the return',
        why: 'The prone position pre-stretches the long head of the biceps femoris across the hip, increasing ROM for hamstring contraction. A deliberate squeeze at the top maximises the contraction signal.',
        increment: { lb: 5, kg: 2 },
      },
    ],
  },
  {
    type: 'upper',
    name: 'Upper',
    exercises: [
      {
        id: 'incline_bb_bench',
        name: 'Incline Barbell Bench (30–45°)',
        sets: 3,
        repRange: [6, 8],
        effort: '2 RIR',
        rest: 180,
        cue: 'Bar to just below the collarbone',
        why: 'Lowering to just below the collarbone naturally rotates the elbows slightly higher, biasing the clavicular head of the pec and anterior deltoid — complementary to the flat bench on Push day.',
        increment: { lb: 5, kg: 2.5 },
        warmupSets: true,
      },
      {
        id: 'weighted_chin_ups',
        name: 'Weighted Chin-Ups',
        sets: 3,
        repRange: [6, 8],
        effort: '2 RIR',
        rest: 180,
        cue: 'Fully supinated grip, 3s controlled descent',
        why: 'Supinated grip places the bicep in a mechanically favourable position for elbow flexion, making this both a compound back movement and direct bicep stimulus.',
        increment: { lb: 5, kg: 2.5 },
        warmupSets: true,
      },
      {
        id: 'flat_db_bench',
        name: 'Flat Dumbbell Bench',
        sets: 3,
        repRange: [8, 10],
        effort: '1–2 RIR',
        rest: 120,
        cue: 'Deep stretch at the bottom',
        why: 'Dumbbells allow greater horizontal shoulder extension than a barbell, deepening the pec stretch. This makes the flat DB bench a strong complement to the flat barbell bench even at the same angle.',
        increment: { lb: 5, kg: 2 },
      },
      {
        id: 'hammer_curl',
        name: 'Unilateral Crossbody Hammer Curl',
        sets: 3,
        repRange: [10, 12],
        effort: '1 RIR',
        rest: 90,
        cue: 'Neutral grip, curl across the body, 4s lowering',
        why: 'The crossbody path supinates the forearm slightly at the top, engaging the brachialis and brachioradialis more than a standard hammer curl — adding arm thickness. The 4-second lowering increases time under tension.',
        increment: { lb: 5, kg: 2 },
      },
      {
        id: 'drag_curl',
        name: 'Close-Grip Drag Curl',
        sets: 3,
        repRange: [8, 12],
        effort: '1 RIR',
        rest: 90,
        cue: 'Drag the bar up the torso, elbows travel back',
        why: 'The dragging motion keeps the elbow behind the torso, maintaining a stretched position of the long head of the bicep throughout — maximising mechanical tension on the part of the bicep that crosses the shoulder joint.',
        increment: { lb: 5, kg: 2 },
      },
      {
        id: 'rope_pushdown',
        name: 'Dual Rope Tricep Pushdown',
        sets: 3,
        repRange: [10, 12],
        effort: '1 RIR',
        rest: 90,
        cue: 'Elbows pinned, flare rope at lockout',
        why: 'Pinning the elbows removes shoulder extension from the movement so the tricep does all the work. Flaring the handles at lockout causes slight internal rotation, fully shortening the lateral and medial heads.',
        increment: { lb: 5, kg: 2 },
      },
    ],
  },
  {
    type: 'lower',
    name: 'Lower',
    exercises: [
      {
        id: 'leg_extension',
        name: 'Leg Extension',
        sets: 3,
        repRange: [12, 15],
        effort: '1 RIR',
        rest: 120,
        cue: 'Let knees bend past 90° on the way down',
        why: 'Allowing the knee to flex past 90° on the descent places the quad in a lengthened position at the bottom, where mechanical tension is highest. Full ROM here provides a strong hypertrophic signal.',
        increment: { lb: 5, kg: 2 },
      },
      {
        id: 'seated_leg_curl',
        name: 'Seated Leg Curl',
        sets: 3,
        repRange: [10, 12],
        effort: '1 RIR',
        rest: 120,
        cue: 'Squeeze at the bottom, control the return',
        why: 'The seated position flexes the hip, pre-stretching the biceps femoris across the hip joint. The hamstring is loaded at a longer length throughout the entire set — strongly associated with superior hypertrophy in the research.',
        increment: { lb: 5, kg: 2 },
      },
      {
        id: 'seated_calf_raise',
        name: 'Seated Calf Raise Machine',
        sets: 4,
        repRange: [12, 15],
        effort: '1 RIR (sets 1–3), failure (set 4)',
        rest: 90,
        cue: 'Knees at 90° isolates the soleus; pause 2s at the stretch',
        why: 'The bent-knee position slackens the gastrocnemius across the knee joint, isolating the soleus, which responds best to higher rep ranges. Pausing at the stretched position eliminates the stretch-shortening reflex.',
        increment: { lb: 5, kg: 2.5 },
        lastSetFailure: true,
      },
      {
        id: 'tibialis_raise',
        name: 'Tibialis Anterior Toe Raise',
        sets: 3,
        repRange: [15, 20],
        effort: '1 RIR (sets 1–2), failure (set 3)',
        rest: 60,
        cue: 'Back against a wall, heels planted',
        why: 'Wall support keeps the shin vertical and allows the tibialis anterior to work from a more lengthened position. Important for shin-splint resilience and ankle stability — often the most undertrained muscle in lower-body programmes.',
        increment: { lb: 2.5, kg: 1.25 },
        lastSetFailure: true,
      },
      {
        id: 'hanging_leg_raise',
        name: 'Hanging Leg Raise',
        sets: 3,
        repRange: [15, 20],
        effort: '1 RIR',
        rest: 60,
        cue: 'No swinging — lift with the core',
        why: 'Hanging eliminates the spinal-flexion compensation that floor-based ab work allows. The deep hip flexors (psoas) get heavy involvement here. If the lower back is fatigued, tuck the knees to reduce the moment arm.',
        increment: { lb: 2.5, kg: 1.25 },
      },
    ],
  },
];

export function getWorkoutDef(type: WorkoutType): WorkoutDef {
  return PROGRAM.find((w) => w.type === type)!;
}

export function getNextWorkoutType(lastType: WorkoutType | null): WorkoutType {
  if (!lastType) return 'push';
  const idx = WORKOUT_ORDER.indexOf(lastType);
  return WORKOUT_ORDER[(idx + 1) % WORKOUT_ORDER.length];
}

export function formatRest(seconds: number): string {
  if (seconds < 60) return `${seconds}s`;
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return s === 0 ? `${m} min` : `${m}m ${s}s`;
}
